
class CustomException(Exception):
    pass

try:
    raise CustomException("La base de donn√©e n'est pas disponible")
except Exception as e:
    print(e)